baseURL = "https://www.davidmboli-idie.com"  # For local development
languageCode = "en-us"
defaultContentLanguage = "en"
title = "David Mboli-Idie"
theme = "gokarna"
publishDir = "public"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    pre = "<span data-feather='book'></span>"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
  
  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 8

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/kingdave4/My-Portfolio.git"
    weight = 9
  
  [[menu.main]]
    name = "Resume"
    url = "static/files/My_resume.pdf"
    weight = 10
  
[params]

  # Choose the color shown when hyperlinks are hovered over
  accentColor = "#FF4D4D"
  favicon = "favicon.ico"
  # Avatar settings
  avatarURL = "/images/my_photo.png"  # Updated path to your avatar image
  avatarSize = "size-l"               # Options: size-xs, size-s, size-m, size-l, size-xl

  # Custom Head HTML (optional)
  customHeadHTML = "<script>console.log('Any HTML')</script>"

  customCSS = ["css/main.css"]
  
  # Date format for posts
  dateFormat = "2 January, 2006"

  mainSections = ["blog"]

  # Meta description for the home page
  description = "IT Support to Cloud Engineer | AZURE & AWS |"

  showBackToTopButton = true
  
  showPostsOnHomePage = true
  
  # Social icons
  socialIcons = [
    {name = "github", url = "https://github.com/kingdave4"},
    {name = "linkedin", url = "https://www.linkedin.com/in/david-mboli-idie-38b974209/"},
    {name = "email", url = "mailto:davidmboli1@email.com"}
  ]

[minify]
    minifyOutput = true
showBackToTopButton = true # true or false for "back to top" button on posts and pages
