name: Deploy Hugo to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install Hugo modules and themes
        run: |
          hugo mod get
          git submodule update --init --recursive

      - name: Build Hugo site
        run: hugo --minify

      - name: Verify Hugo output
        run: ls -la public/

      - name: Upload to Azure Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source 'public' \
              --overwrite
