name: Deploy Hugo Site to Azure Static Web App

on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.7' # Update to your Hugo version
          extended: true

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          action: 'upload'
          app_location: "/"
          output_location: "public"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}


# Note: Make sure to set the AZURE_STATIC_WEB_APPS_API_TOKEN secret in your GitHub repository settings.
