name: Deploy Hugo to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Hugo modules and themes
        run: |
          hugo mod get
          git submodule update --init --recursive

      - name: Build Hugo site
        run: hugo

      - name: Verify Hugo output
        run: ls -la public/

      # Add Azure authentication step
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
              --destination '$web' \
              --source 'public' \
              --overwrite \
              --auth-mode key \
              --subscription "d9b9463a-c7d3-4f78-beb4-9053a43f2f05"